AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
    Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Documentation:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 80
Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']
