coins:
  individual:
    low:
      0:
        cp:
          dices: 5
          multiplier: 1
      1:
        cp:
          dices: 5
          multiplier: 1
      2:
        cp:
          dices: 5
          multiplier: 1
      3:
        cp:
          dices: 5
          multiplier: 1
      4:
        cp:
          dices: 5
          multiplier: 1
      5:
        cp:
          dices: 5
          multiplier: 1
      6:
        cp:
          dices: 5
          multiplier: 1
      7:
        cp:
          dices: 5
          multiplier: 1
      8:
        cp:
          dices: 5
          multiplier: 1
      9:
        cp:
          dices: 5
          multiplier: 1
      10:
        cp:
          dices: 5
          multiplier: 1
      11:
        cp:
          dices: 5
          multiplier: 1
      12:
        cp:
          dices: 5
          multiplier: 1
      13:
        cp:
          dices: 5
          multiplier: 1
      14:
        cp:
          dices: 5
          multiplier: 1
      15:
        cp:
          dices: 5
          multiplier: 1
      16:
        cp:
          dices: 5
          multiplier: 1
      17:
        cp:
          dices: 5
          multiplier: 1
      18:
        cp:
          dices: 5
          multiplier: 1
      19:
        cp:
          dices: 5
          multiplier: 1
      20:
        cp:
          dices: 5
          multiplier: 1
      21:
        cp:
          dices: 5
          multiplier: 1
      22:
        cp:
          dices: 5
          multiplier: 1
      22:
        cp:
          dices: 5
          multiplier: 1
      23:
        cp:
          dices: 5
          multiplier: 1
      24:
        cp:
          dices: 5
          multiplier: 1
      25:
        cp:
          value: 5
          multiplier: 1
      26:
        cp:
          value: 5
          multiplier: 1
      27:
        cp:
          value: 5
          multiplier: 1
      28:
        cp:
          value: 5
          multiplier: 1
      29:
        cp:
          value: 5
          multiplier: 1
      30:
        sp:
          dices: 4
          multiplier: 1
      31:
        sp:
          dices: 4
          multiplier: 1
      32:
        sp:
          dices: 4
          multiplier: 1
      33:
        sp:
          dices: 4
          multiplier: 1
      34:
        sp:
          dices: 4
          multiplier: 1
      35:
        sp:
          dices: 4
          multiplier: 1
      36:
        sp:
          dices: 4
          multiplier: 1
      37:
        sp:
          dices: 4
          multiplier: 1
      38:
        sp:
          dices: 4
          multiplier: 1
      39:
        sp:
          dices: 4
          multiplier: 1
      40:
        sp:
          dices: 4
          multiplier: 1
      41:
        sp:
          dices: 4
          multiplier: 1
      42:
        sp:
          dices: 4
          multiplier: 1
      43:
        sp:
          dices: 4
          multiplier: 1
      44:
        sp:
          dices: 4
          multiplier: 1
      45:
        sp:
          dices: 4
          multiplier: 1
      46:
        sp:
          dices: 4
          multiplier: 1
      47:
        sp:
          dices: 4
          multiplier: 1
      48:
        sp:
          dices: 4
          multiplier: 1
      49:
        sp:
          dices: 4
          multiplier: 1
      50:
        sp:
          dices: 4
          multiplier: 1
      51:
        sp:
          dices: 4
          multiplier: 1
      52:
        sp:
          dices: 4
          multiplier: 1
      53:
        sp:
          dices: 4
          multiplier: 1
      54:
        sp:
          dices: 4
          multiplier: 1
      55:
        sp:
          dices: 4
          multiplier: 1
      56:
        sp:
          dices: 4
          multiplier: 1
      57:
        sp:
          dices: 4
          multiplier: 1
      58:
        sp:
          dices: 4
          multiplier: 1
      59:
        sp:
          dices: 4
          multiplier: 1
      60:
        ep:
          dices: 3
          multiplier: 1
      61:
        ep:
          dices: 3
          multiplier: 1
      62:
        ep:
          dices: 3
          multiplier: 1
      63:
        ep:
          dices: 3
          multiplier: 1
      64:
        ep:
          dices: 3
          multiplier: 1
      65:
        ep:
          dices: 3
          multiplier: 1
      66:
        ep:
          dices: 3
          multiplier: 1
      67:
        ep:
          dices: 3
          multiplier: 1
      68:
        ep:
          dices: 3
          multiplier: 1
      69:
        ep:
          dices: 3
          multiplier: 1
      70:
        gp:
          dices: 3
          multiplier: 1
      71:
        gp:
          dices: 3
          multiplier: 1
      72:
        gp:
          dices: 3
          multiplier: 1
      73:
        gp:
          dices: 3
          multiplier: 1
      74:
        gp:
          dices: 3
          multiplier: 1
      75:
        gp:
          dices: 3
          multiplier: 1
      76:
        gp:
          dices: 3
          multiplier: 1
      77:
        gp:
          dices: 3
          multiplier: 1
      78:
        gp:
          dices: 3
          multiplier: 1
      79:
        gp:
          dices: 3
          multiplier: 1
      80:
        gp:
          dices: 3
          multiplier: 1
      81:
        gp:
          dices: 3
          multiplier: 1
      82:
        gp:
          dices: 3
          multiplier: 1
      83:
        gp:
          dices: 3
          multiplier: 1
      84:
        gp:
          dices: 3
          multiplier: 1
      85:
        gp:
          dices: 3
          multiplier: 1
      86:
        gp:
          dices: 3
          multiplier: 1
      87:
        gp:
          dices: 3
          multiplier: 1
      88:
        gp:
          dices: 3
          multiplier: 1
      89:
        gp:
          dices: 3
          multiplier: 1
      90:
        gp:
          dices: 3
          multiplier: 1
      91:
        gp:
          dices: 3
          multiplier: 1
      92:
        gp:
          dices: 3
          multiplier: 1
      93:
        gp:
          dices: 3
          multiplier: 1
      94:
        gp:
          dices: 3
          multiplier: 1
      95:
        gp:
          dices: 3
          multiplier: 1
      96:
        gp:
          dices: 3
          multiplier: 1
      97:
        pp:
          dices: 1
          multiplier: 1
      98:
        pp:
          dices: 1
          multiplier: 1
      99:
        pp:
          dices: 1
          multiplier: 1
      100:
        pp:
          dices: 1
          multiplier: 1
